export const tableOption = {
  "border": true,
  "index": true,
  "indexLabel": "序号",
  "stripe": true,
  "menuAlign": "center",
  "align": "center",
  "dialogDirection": "rtl",
  "searchMenuSpan": 6,
  "column": [
	  {
      "type": "input",
      "label": "主键id",
      "prop": "id"
    },	  {
      "type": "input",
      "label": "创建时间",
      "prop": "createTime"
    },	  {
      "type": "input",
      "label": "创建人",
      "prop": "createBy"
    },	  {
      "type": "input",
      "label": "修改时间",
      "prop": "updateTime"
    },	  {
      "type": "input",
      "label": "修改人",
      "prop": "updateBy"
    },	  {
      "type": "input",
      "label": "逻辑删除标记(1.正常2.删除)",
      "prop": "enable"
    },	  {
      "type": "input",
      "label": "排序号",
      "prop": "sort"
    },	  {
      "type": "input",
      "label": "备注",
      "prop": "remark"
    },	  {
      "type": "input",
      "label": "队员姓名",
      "prop": "name"
    },	  {
      "type": "input",
      "label": "职位",
      "prop": "position"
    },	  {
      "type": "input",
      "label": "联系方式",
      "prop": "phone"
    },	  {
      "type": "input",
      "label": "简介",
      "prop": "introduction"
    },	  {
      "type": "input",
      "label": "用户id(崇文路系统)",
      "prop": "allUser"
    },	  {
      "type": "input",
      "label": "所属队伍",
      "prop": "teamInfo"
    }  ]
}
